# Generated by Django 3.1.7 on 2021-03-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='img/members')),
                ('role', models.CharField(choices=[('general', 'General Member'), ('head', 'Head of Laboratory'), ('assistant', 'Assistant Laboratory'), ('former', 'Former Member')], default='Former Member', max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('generation', models.CharField(max_length=3)),
                ('department', models.CharField(choices=[('Bachelor of Informatics', 'Bachelor of Informatics'), ('Bachelor of Information Technology', 'Bachelor of Information Technology'), ('Others', 'Others')], default='Bachelor of Informatics', max_length=50)),
                ('student_year', models.CharField(max_length=4)),
                ('linkedin', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Members',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='img/topics')),
                ('study', models.CharField(choices=[('advance', 'Advance'), ('basic', 'Basic'), ('other', 'Other')], default='Basic', max_length=10)),
                ('description', models.TextField(max_length=10000)),
                ('time', models.CharField(max_length=250)),
                ('tutor', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='Disabled', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Topics',
            },
        ),
    ]
