# Generated by Django 3.1.7 on 2021-03-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=500)),
                ('publisher', models.CharField(max_length=250)),
                ('abstract', models.CharField(max_length=10000)),
                ('year', models.CharField(max_length=4)),
                ('link', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Publications',
            },
        ),
    ]
