# Generated by Django 3.1.7 on 2021-03-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='abstract',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='publication',
            name='link',
            field=models.CharField(max_length=500),
        ),
    ]
